### ISSUE TITLE
[BUG]: Crash on startup, when an other window is prioritize

### ISSUE THREAD

**Issue by Tim-Odermatt** [SpokenWig620933/Create-BasicAdditions#4]
-------------------------
**Version(s)**
MC-Ver: 1.20.1 Forge
Mod-Ver: 1.0.1a
Create-Ver: 0.5.1.f
-------------------------
**Describe the bug**
Crash on startup, when an other window is prioritize.
I will try to disable some other mods and see if it continues to happen.
The chance for the game to crash when i am tabbed out of minecraft on load, seems to be around 50%?

-------------------------
**Steps To Reproduce** 
1. Launch game, 
2. Tab outside the Game window
3. Forge Load fails and it tells me Create: basic Additions is the problem
-------------------------
**Expected Behavior** 
1. Launch Game
2. Game Launches

-------------------------
**Screenshots** 
Will Add it later in about 10h, including a crashlog and modlist.

-------------------------

**Comment by SpokenWig620933** [comment]
Hello, I see you haven't added a screenshot or error message yet.
If you could please do this so I have better context on how this could have happened.

**Comment by Tim-Odermatt** [comment]
Crashlog
![image](https://github.com/SpokenWig620933/Create-BasicAdditions/assets/91256797/7bbab80e-5dfd-47c4-a730-6d1ec2410b5c)

**Comment by Tim-Odermatt** [comment]
Minecraft Crashlog
https://mclo.gs/IyBkHEw

**Comment by Tim-Odermatt** [comment]
Latest Log
https://mclo.gs/eYxtMeS

**Comment by Tim-Odermatt** [comment]
modlist:
.connector
additionaladditions-6.0.1.jar
additionalentityattributes-forge-1.4.0.5+1.20.1.jar
AdvancementPlaques-1.20.1-forge-1.4.10.jar
AmbientEnvironment-forge-1.20.1-11.0.0.1.jar
amendments-1.20-1.1.6.jar
appleskin-forge-mc1.20.1-2.5.1.jar
architectury-9.2.14-forge.jar
argonauts-forge-1.20.1-1.0.8.jar
athena-forge-1.20.1-3.1.1.jar
balancedflight-1.20.1_v2.2.0.jar
balm-forge-1.20.1-7.2.2.jar
BedBenefits-Forge-1.20.1-13.0.3.jar
bellsandwhistles-0.4.3-1.20.x.jar
better-end-4.0.11.jar.disabled
BetterAdvancements-1.20.1-0.3.2.162.jar
betterarcheology-1.1.6-1.20.1.jar
bettersafebed-forge-1.20-9.jar
BetterSmithingTable-1.1.0-Forge-1.20.jar
BetterThirdPerson-Forge-1.20-1.9.0.jar
bigcontraptions-1.0.jar
blur-forge-3.1.1.jar
Boat-Item-View-Forge-1.20.1-0.0.5.jar
bobberdetector-0.1.9-1.20.1.jar
Bookshelf-Forge-1.20.1-20.1.9.jar
botarium-forge-1.20.1-2.3.3.jar
brightnessslider-forge-1.0-1.20.jar
cadmus-forge-1.20.1-1.0.7.jar
caelus-forge-3.1.0+1.20.jar
calcmod-forge-1.20.1-1.3.0.jar
catalogue-forge-1.20.1-1.8.0.jar
cat_jam-forge-mc1.20-1.2.1.jar
cavedust-2.0.4-1.20.1-forge.jar
charmofundying-forge-6.4.5+1.20.1.jar
cherishedworlds-forge-6.1.4+1.20.1.jar
Chunky-1.3.136.jar
citresewn-1.20.1-5.jar
clean_tooltips-1.0-forge-1.20.1.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.3.jar
collective-1.20.1-7.36.jar
comforts-forge-6.3.5+1.20.1.jar
Connector-1.0.0-beta.40+1.20.1.jar.disabled
ConnectorExtras-1.10.0+1.20.1.jar.disabled
Controlling-forge-1.20.1-12.0.2.jar
copiescats-0.0.1-1.20.1.jar
CraterLib-Forge-1.20-1.1.1.jar
create-1.20.1-0.5.1.f.jar
create-confectionery1.20.1_v1.1.0.jar
create-new-age-forge-1.20.1-1.1.2.jar
create-structures-0.1.1-1.20.1-FORGE.jar
create-stuff-additions1.20.1_v2.0.4a.jar
create-track-map-1.4+mc1.20.1-neoforge.jar
createaddition-1.20.1-1.2.2.jar
createadditionplus-1.2.0-1.20.jar
createbigcannons-forge-1.20.1-0.5.3.b.jar
CreateCasing-1.20.1-1.6.0.jar
createdeco-2.0.1-1.20.1-forge.jar
createdieselgenerators-1.20.1-1.2h.jar
creategoggles-1.20.1-0.5.5.f-[FORGE].jar
CreateMoreAutomation-1.20.1-0.4.0.jar
createoreexcavation-1.20-1.4.2.jar
createutilities-0.2.0+1.20.1.jar
create_aquatic_ambitions-1.20.1-1.0.0.jar
create_basic_additions-1.20.1-1.0.1a-forge.jar
create_central_kitchen-1.20.1-for-create-0.5.1.f-1.3.10.jar
create_connected-0.7.2-mc1.20.1-all.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.8.jar
create_enchantment_industry_plus-1.20.1-1.1.0.jar
create_high_pressure-1.1.0.jar
create_jetpack-forge-4.2.1.jar
create_mechanical_spawner-1.20.1-0.0.14.e-22.jar
create_misc_and_things_ 1.20.1_4.0A.jar
create_oxidized-0.1.1.jar
create_prismarine_automation-1.20.1-forge.jar
create_recycle_1.0.2_forge_1.20.1.jar
curios-forge-5.7.0+1.20.1.jar
curiotiab-1.20.1-2.0.2.jar
CutThrough-v8.0.2-1.20.1-Forge.jar
design_decor-0.2a-1.20.1.jar
DiagonalFences-v8.1.3-1.20.1-Forge.jar
Ding-1.20.1-Forge-1.4.1.jar
dismountentity-1.20.1-3.2.jar
Display Case-forge-1.20-1.0.8.jar
DMMTTBA-forge-1.20.1-1.0.2.jar
dummmmmmy-1.20-1.8.14.jar
dynmus-v2.3.2+1.20-forge.jar
eating-animation-1.20+1.9.5.jar
elytraslot-forge-6.3.0+1.20.1.jar
elytratrims-forge-2.0.3+1.20.1.jar
embeddium-0.3.11+mc1.20.1.jar
embeddiumplus-1.20.1-v1.2.5.jar
emissive-plugin-1.20.1-2.0.4-forge.jar
entityculling-forge-1.6.2-mc1.20.1.jar
entity_model_features_forge_1.20.1-1.3.jar
entity_texture_features_forge_1.20.1-5.2.3.jar
EquipmentCompare-1.20.1-forge-1.3.7.jar
euphonium-1.0.1+1.20.jar
EuphoriaPatcher-0.3.0-forge.jar
everycomp-1.20-2.6.35.jar
Excavar-1.20.1-3.1.0.jar
exposure-1.20.1-1.4.0-forge.jar
fabric-api-0.92.0+1.11.3+1.20.1.jar
Fallingleaves-1.20.1-2.1.0.jar
FarmersDelight-1.20.1-1.2.4.jar
FastLeafDecay-31.jar
fastportals-1.0.3-forge 1.20.x.jar
ferritecore-6.0.1-forge.jar
FpsReducer2-forge-1.20-2.5.jar
freecam-forge-modrinth-1.2.1+1.20.jar
fusion-1.1.1-forge-mc1.20.1.jar
garnished-1.6.3+1.20.1.jar
geckolib-forge-1.20.1-4.4.2.jar
heracles-forge-1.20.1-1.1.10.jar
highlight-forge-1.20-2.0.1.jar
Highlighter-1.20.1-forge-1.1.9.jar
Iceberg-1.20.1-forge-1.1.21.jar
interiors-0.5.2+mc1.20.1-FORGE.jar
item-filters-forge-2001.1.0-build.59.jar
ItemLocks-Forge-1.20.1-1.3.8.jar
Jade-1.20.1-forge-11.8.0.jar
JadeAddons-1.20.1-forge-5.2.2.jar
jeed-1.20-2.1.7.jar
jumpboat-1.20.0-1.0.5.jar
jumpoverfences-forge-1.20.1-1.3.1.jar
justenoughbreeding-forge-1.20.x-1.0.12.jar
JustEnoughProfessions-forge-1.20.1-3.0.1.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
kotlinforforge-4.10.0-all.jar
Ksyxis-1.2.2.jar
kubejs-create-forge-2001.2.5-build.2.jar
kubejs-forge-2001.6.4-build.138.jar
lazurite-1.0.3+mc1.20.1.jar
LibX-1.20.1-5.0.13.jar
lmft-1.0.4+1.20.1-forge.jar
loadingbackgrounds-1.1.0-forge.jar
Log-Begone-Forge-1.20.1-1.0.8.jar
Lychee-1.20.1-forge-5.1.9.jar
make_bubbles_pop-0.2.0-forge-mc1.19.4+.jar
MEED-1.20.1-3.8.jar
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar
memoryleakfix-forge-1.17+-1.1.5.jar
modelfix-1.14.jar
modernfix-forge-5.15.0+mc1.20.1.jar
molten_vents-1.20.1-2.0.6.jar
molten_vents_custom_blocks.json
moonlight-1.20-2.10.10-forge.jar
moremcmeta-1.20.1-4.4.7-forge.jar
MouseTweaks-forge-mc1.20-2.25.jar
Necronomicon-Forge-1.4.2.jar
nerb-1.20.1-0.3-FORGE.jar
notenoughanimations-forge-1.7.1-mc1.20.1.jar
oculus-flywheel-compat-1.20.1-0.2.2.jar
oculus-mc1.20.1-1.6.15a.jar
okzoomer-forge-1.20-3.0.1.jar
OpenLoader-Forge-1.20.1-19.0.3.jar
PacketFixer-forge-1.20.1-1.2.8.jar
passiveshield-1.20.1-3.4.jar
PickUpNotifier-v8.0.0-1.20.1-Forge.jar
Ping-Wheel-1.8.0-forge-1.20.1.jar
polymorph-forge-0.49.2+1.20.1.jar
ponderjs-1.20.1-1.3.1.jar
portable-crafting-2.2.1+1.19.3.jar
PuzzlesLib-v8.1.17-1.20.1-Forge.jar
Quark-4.0-438.jar
QuarkOddities-1.20.1.jar
rebind_narrator-forge-1.20.1-2.0.2.jar
rechiseled-1.1.5c-forge-mc1.20.jar
rechiseledcreate-1.0.2-forge-mc1.20.jar
REICustomCommand-1.20.1-forge-2.1.0.jar
REIPluginCompatibilities-forge-12.0.93.jar
rer-2.9.0.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
resourcefullib-forge-1.20.1-2.1.23.jar
ResourcePackOverrides-v8.0.3-1.20.1-Forge.jar
Resourcify (1.20-1.20.1-forge)-1.3.1.jar
rhino-forge-2001.2.2-build.18.jar
roughly-enough-config-screens-1.20.1-forge-1.4.1.jar
RoughlyEnoughItems-12.0.684-forge.jar
RoughlyEnoughProfessions-forge-1.20.1-2.0.2.jar
Rrls-3.2.0-1.20.1-forge.jar
rubidium-extra-0.5.4.2+mc1.20.1-build.118.jar
seamless-2.2.2-forge-1.20.1.jar
Searchables-forge-1.20.1-1.0.2.jar
SimpleRPC-forge-1.20-3.2.4.jar
skinlayers3d-forge-1.6.2-mc1.20.1.jar
sliceanddice-forge-3.2.0.jar
smarterfarmers-1.20-1.8.3.jar
snowundertrees-1.20.1-1.4.3.jar
sophisticatedbackpacks-1.20.1-3.20.1.1012.jar
sophisticatedcore-1.20.1-0.6.3.553.jar
sound-physics-remastered-forge-1.20.1-1.3.1.jar
spark-1.10.53-forge.jar
starlight-1.1.2+forge.1cda73c.jar
Steam_Rails-1.5.3+forge-mc1.20.1.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17-forge-mc1.20.1.jar
supplementaries-1.20-2.8.6.jar
suppsquared-1.20-1.1.14.jar
tagtooltips-1.20.1-1.0.jar
TaxFreeLevels-1.3.9-forge-1.20.2.jar
textrues_embeddium_options-0.1.5+mc1.20.1.jar
tia-1.20-1.1-forge.jar
time-in-a-bottle-4.0.4-mc1.20.1.jar
Tips-Forge-1.20.1-12.0.5.jar
toms_storage-1.20-1.6.5.jar
trade-cycling-forge-1.20.1-1.0.10.jar
TrampleNoMore-Forge-1.20.1-13.0.3.jar
TravelAnchors-1.20.1-5.0.0.jar
TravelersTitles-1.20-Forge-4.0.2.jar
treeharvester-1.20.1-8.7.jar
valkyrienskies-120-2.3.0-beta.5.jar
vanilla-refresh-CT-1.4.19a.jar
visuality-forge-2.0.2.jar
VisualWorkbench-v8.0.0-1.20.1-Forge.jar
v_slab_compat-1.20-2.3.jar
waystones-forge-1.20-14.1.3.jar
WaystonesTeleportPets-1.20-1.20.1--1.2.jar
whats-that-slot-forge-1.3.4+1.20.1.jar
XaerosWorldMap_1.37.8_Forge_1.20.jar
Xaeros_Minimap_23.9.7_Forge_1.20.jar
xaeros_waystones_compability-1.19.2-1.20.1--1.0.jar
YungsApi-1.20-Forge-4.0.4.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBridges-1.20-Forge-4.0.3.jar
YungsExtras-1.20-Forge-4.0.3.jar
Zeta-1.0-14.jar

**Comment by Tim-Odermatt** [comment]
Every ca. 5th launch of Minecraft results in a crash.

but it only happens when i Launch the game and Prioritize another window. like Firefox

**Comment by Tim-Odermatt** [comment]
@SpokenWig620933 you can put this issue on-hold.

When I have more information about why my modpack randomly crashes, i will message you.

**Comment by Tim-Odermatt** [comment]
@SpokenWig620933 

This may be a weird request, but could i obtain the Source Code?

**Comment by Tim-Odermatt** [comment]
Missing version on Modrinth: 1.0.2

https://modrinth.com/mod/create-basic-additions/versions?l=forge&g=1.20.1

https://www.curseforge.com/minecraft/mc-mods/create-basic-additions/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1

**Comment by SpokenWig620933** [comment]
Thanks for the Reminder! Forgot Modrinth existed as well for a minute there.
I'll await more information when and if it comes on this issue.

**Comment by Tim-Odermatt** [comment]
Fixed since latest create-basic-additions version: 1.0.2

Thank you. 😄
